import React from 'react'

const Privacy_policy = () => {
    return (
        <div>
            <h1> Privacy Policy</h1>
            <br />
            <h2>Privacy Policy</h2>

            <b>Updated at 2022-05-17</b> <br />

            Smarteducates (‘hoe,” “our,” or “us”) is committed to protecting your privacy This Privacy Policy explains how your personal information is collected, used, and disclosed by smarteducates This Privacy Policy applies to our website, https//smarteducates.in/, and its associated subdomains (collectively, our “Service”) By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service<br /><br />

            <h2>Definitions and key terms</h2>

            <h3> For this Privacy Policy</h3>

            • Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.<br />

            • Company: when this policy mentions ‘Company° ‘we: °us,” or ‘our,. it refers to smarteducates that is responsible for your information under this Privacy Policy.<br />

            • Country: where smarteducates or the owners/founders of smarteducates are based, in this case is india.<br />

            • Customer: refers to the company, organization or person that signs up to use the smarteducates Service to manage the relationships with your consumers or service users.<br />

            • Device: any Internet connected device such as a phone, tablet computer or any other deuce that can be used to vislt smarteducates and use the services.<br />

            • IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address These numbers are usually assigned in geographic blocks An IP address can often be used to identity the locator from which a device is connecting to the Internet<br />

            • Personnel: refers to those individuals who are employed by smarteducates or are under contract to perform a service on behalf of one of the parties<br />

            • Personal Data: any information that directly, indirectly, or in connection wrth other information — induding a personal identification number — allows for the identification or identifiability of a natural person<br />

            • Service: refers to the service provided by smarleducates as described in the relative terms (if available) and on this platform<br />

            • Third-party service: refers to adverbsers, contest sponsors, promotional and marketing parhers, and others who provide our content or whose products or services we think may interest you • Website: smarleducates’s site, which can be accessed via this URL https Thmarteducates in/ • You: a person or entity that is registered with smarteducates to use the Sermces<br /><br />

            <h2> What Information Do We Collect?</h2>

            We collect information from you when you visit our service, remster, place an order subscribe to our newsletter respond to a survey or fill out a form<br />

            • Name / Username<br />

            • Phone Numbers<br />

            • Email Addresses<br />

            • Mailing Addresses<br /><br />

            <h2> How Do We Use The Information We Collect?</h2>

            Any of the information we collect from you may be used in one of the following ways<br />

            • To personalize your experience (your information helps us to boiler respond to your individual needs) • To improve our service (we continually strive to improve our service offerings based on the information and feedback we receive from you)<br />

            • To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)<br />

            • To process transadons<br />

            • To administer a contest, promotion, survey or other site feature<br />

            • To send penothc emails<br /><br />

            <h2>When do we use customer information from third parties?</h2>

            We receive some information from the third parties when you contact us. For example, when you submit your email address tousle show interest in becoming our customer, we receive information from a third party that provides automated fraud detection services to us. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these webstes and changing your privacy settings.<br /><br />

            <h2>Do we share the information we collect with third parties?</h2>

            We may share the information that we collect, both personal and non-personal, with third pates such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other<br />

            business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.<br />

            We may engage trusted [hull party service providers to perform functions and provide services to us, such as resting and maintaining our servers and our service, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through our platform We are likely share your personal information, and possibly some non-personal information, with these third pates to enable them to perform these services for us and for you<br />

            We may share portions of our log file data, including IP addresses, for analytic purposes with third pates such as web analytics partners, application developers, and ad networks If your IP address is shared, it may be used to estimate general location and other technographics such as connector speed, whether you have visited the service in a shared location, and type of device used to visa the service They may aggregate information about our advertising and what you see on the service and then provide auditing, research and reporting torus and our advertisers 6:<br />

            We may also disclose personal and non-personal information about you to the government or law enforcement officials or private pates as we, in our sole discretion, believe necessary or appropriate in order to respond to dams, legal process (including subpoenas), to
            protect our rights and interests or those of a third party the safety of the public or any person, to prevent, stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations

            <h2>Where and when is information collected from customers and end users?</h2>

            We will collect personal information that you abut to us We may also receive personal information about you from third parties as ascribed above<br /><br />

            <h2>How Do We Use Your Email Address?</h2>

            By submitting your email address on this website, you agree to receive emails from us You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscnbe option that is included in the respective email We only send emails to people who have authonzed us to contact them, either directly, or through a third party We do not send unsolicited commercial emails, because we hate spam as much as you do By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facetzak, where we display custom advertising to specific people who have opted-in to receive communications from us Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order It however you have provided the same email to us through another method, we may use dyer any of the purposes stated in this Policy Note If at any time you would Ike to unsubscnbe from receiving future emails, we include detailed &subscribe instructions at the bottom of each email<br /><br />

            <h2>Could my information be transferred to other countries?</h2>

            We have incorporated in India Information collected via our website, through direct interactions with you, or from use of our help services may be transferred horn time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans-border transfer and hosting of such information<br /><br />

            <h2>Is the information collected through our service secure?</h2>

            We take precautions to protect the security of your information We have physical, electron., and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information However, norther people nor security systems are foolproof, including encryption systems, In addition, people can comma intentional comes, make mistakes entail to follow policies, Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security It applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty<br /><br />

            <h2>Can I update or correct my information?</h2>

            The rights you have to request updates or corrections to the information we collect depend on your relationship with us. Personnel may update or correct their information as detailed in our internal company employment policies. Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us in order to) update or correct your personally identifiable information, (2) change your preferences with respect to communications and other information you receive horn us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph), by canceling your account Such updates, corrections, changes, and deletions will have no effect on other information that we maintain or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion. To protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify,r your identity before granting you profile access or making corrections. You are responsible for maintaining the secrecy of your unique password and account information at all times. You should be aware that it is not technologically possible to remove each and every record of the information you have provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after receiving your request all personal information stored in databases we actively use, and other readily searchable media will be updated, corrected, changed or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable. If you are an end user and wish to update, delete, or receive any information we have about you, you may do so by contacting the organization of which you are a customer.<br /><br />

            <h2>Sale of Business</h2>

            We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of us or any of its Corporate Affiliates (as defined herein), or that portion of us or any of its Corporate Affiliates to which the Service relates, rain the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy<br /><br />

            <h2>Affiliates</h2>

            We may disclose information (including personal information) about you to our Corporate Affiliates For purposes of this Privacy Policy, “Corporate Affiliate” means any person or entity which directly or indirectly controls, is controlled by or is under common control with us, whether by ownership or otherwise Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy<br /><br />

            <h2>How Long Do We Keep Your Information?</h2>

            We keep your information only so long as we need It to provide service to you and fulfill the purposes deserted in this policy This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need to keep it to comply with our legal or regulatory obligations, we’ll either remove it from our systems or depersonalize it so that we can’t identify you<br /><br />

            <h2>How Do We Protect Your Information?</h2>

            We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information We offer the use of a secure server All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential After a transaction, your private information (credit cards, social security numbers, financials, Ac) is never kept on file We cannot, however, ensure or warrant the absolute security of any information you transmit to us or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards<br /><br />

            <h2>Governing Law</h2>

            The laws of India, excluding its conflicts of law rules, shall govern this Agreement and your use of our service Your use of our service may also be submitted to other local, state, national, or international laws<br />

            Your Consent<br />

            By using our service registering an account, or making a purchase, you consent to this Privacy Policy<br /><br />

            <h2> Links to Other Websites</h2>

            This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by . We are not responsible for the content accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by u, Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies Such third parties may use their own cookies or other methods to collect information about you<br /><br />

            <h2>Cookies</h2>

            We use “Cookies. to identify the areas of our website that you have visited. A cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to personalize the Content that you see on our website. Most web browsers can be set to disable the use of Cookie, However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all We never place Personally Identifiable Information in Cookies.<br /><br />

            <h2>Payment Details</h2>

            In respect to any credit card or other payment processing details you have provided us, we commit that this confidential formation II be stored in the most secure manner possible<br /><br />

            <h2>Kids’ Privacy</h2>

            We do not address anyone under the age of 13 We do not knowingly collect personally identifiable information from anyone under the age of 13 If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please Contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without Benfica on of parental consent, We take steps to remove that information from our servers.<br /><br />

            <h2>Changes To Our Privacy Policy</h2>

            If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below.<br /><br />

            <h2>Third-Party Services</h2>

            We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services (“Third- Party Services”)<br />

            You acknowledge and agree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Son/Ices<br />

            Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties terms and conditions.<br /><br />
        </div>
    )
}

export default Privacy_policy